### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Ofrila** [Cameltr/RGTSI#1]
Thanks for your sharing.But I can't find the dataset 'DPED10K', could you support the link of the dataset? Thank you

**Comment by Cameltr** [comment]
We have extended our dataset DPED10K to DPED50K in our new work **TransRef**. You can download DPED50K from [TransRef](https://github.com/Cameltr/TransRef)

**Comment by Egkang-Luis** [comment]
Thanks for sharing code and concept it was great to me to study image process.

By the way, I can't download dataset at Baidu...

Is there any other download link?
