### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by Egkang-Luis** [Cameltr/RGTSI#3]
Thanks for sharing code and concept it was great to me to study image process.

By the way, I can't download dataset at Baidu...

Is there any other download link?

Thanks.

**Comment by Cameltr** [comment]
Sorry for the trouble. I just uploaded the dataset to Google Drive and added the link to Readme. You can download it from [here](https://drive.google.com/drive/folders/1nBFG6EAQTW-G55Nh4YwFaiU_gnIo8Qks).

**Comment by Egkang-Luis** [comment]
Thanks for providing promptly.

By the way, I'm new people to study deep learning. Can I ask something personally? If you can share your prefer method whatever wechat or email to contact you, I'll contact.
