### ISSUE TITLE
--input_mask_root  What data should be used.

### ISSUE THREAD

**Issue by a13049162951** [Cameltr/RGTSI#8]
There is no such data in the data set you gave, and I do not know how to get the relevant mask.

**Comment by Cameltr** [comment]
Our model is trained on the irregular mask dataset provided by [Liu et al](https://arxiv.org/abs/1804.07723). You can download publically available Irregular Mask Dataset from their [website](http://masc.cs.gmu.edu/wiki/partialconv).

**Comment by a13049162951** [comment]
This page cannot be opened.
